### ISSUE TITLE
/kbsync ping Command showing ping as "nullms"

### ISSUE THREAD

**Issue by TehNitro** [CASELOAD7000/knockback-sync#22]
![image](https://github.com/user-attachments/assets/69fdc956-80dc-4460-bddc-907079a739e5)

(This is for every player)

**Comment by Axionize** [comment]
Make sure you have runnable enabled and just wait, ping will load in sooner or later.

Alternatively if you are behind some kind of proxy setup ping packets may not be passed properly (though this is unlikely). 

What version of the plugin are you using, what does your config look like, and what environment are you running on?

**Comment by CASELOAD7000** [comment]
make sure the player is hit before checking their ping

**Comment by Axionize** [comment]
I've updated made some changes to the messages in the process of adding fabric support that will be reflected here eventually. The command will now show your estimated ping instead of just nullms before a pong has been received.

**Comment by TehNitro** [comment]
> make sure the player is hit before checking their ping

That seemed to work!
