### ISSUE TITLE
Player is ineligible for KnockbackSync

### ISSUE THREAD

**Issue by TheIdiot0** [CASELOAD7000/knockback-sync#31]
It tells me that error when I try to enable knockbacksync for a geyser player.
![image](https://github.com/user-attachments/assets/d053d693-d1ad-4467-9773-76bc62d55167)

**Comment by CASELOAD7000** [comment]
Bedrock players are not supported because their knockback is completely different than java. We may add compatibility in the future, but it has never been a priority.
