### ISSUE TITLE
Silly goober bug

### ISSUE THREAD

**Issue by TehNitro** [CASELOAD7000/knockback-sync#4]
Sometimes just happens when you fight
<img width="1051" alt="Screenshot 2024-09-30 at 09 17 44" src="https://github.com/user-attachments/assets/e2f08b5d-eb4b-4740-a440-ec2ba0f57eb4">

**Comment by CASELOAD7000** [comment]
Try the latest release to see if it fixes your issue. Thanks for reporting

**Comment by TehNitro** [comment]
Hey, the latest release doesn't include a jar

**Comment by CASELOAD7000** [comment]
Whoops...

**Comment by CASELOAD7000** [comment]
should be good now

**Comment by TehNitro** [comment]
Thank ya
