### ISSUE TITLE
Wrong version in paper.yml

### ISSUE THREAD

**Issue by TehNitro** [CASELOAD7000/knockback-sync#5]
Pretty sure you forgot to change the version in the paper.yml (it's making the update checker falsely say that the latest update is out of date)

**Comment by TehNitro** [comment]
Also you're mixing "1.31" and "1.3.1"

**Comment by CASELOAD7000** [comment]
Thanks for reporting

**Comment by CASELOAD7000** [comment]
should now be fixed
