### ISSUE TITLE
Does this plugin cause issues with anticheats?

### ISSUE THREAD

**Issue by Hwaanx** [CASELOAD7000/knockback-sync#6]

**Comment by TehNitro** [comment]
Some anti-cheats sometimes change knockback (probably to prevent velocity cheats)

**Comment by Hwaanx** [comment]
Take for example grim anticheat does it cause any issues with that?

**Comment by TehNitro** [comment]
I tried using kb-sync with GrimAC, the knockback was very odd

**Comment by CASELOAD7000** [comment]
> I tried using kb-sync with GrimAC, the knockback was very odd

does this still happen with the latest version?

**Comment by TehNitro** [comment]
It does

**Comment by notstevy** [comment]
I would love to use this plugin with the `GrimAC`, but if the knockback is even worse than without `knockback-sync`, I can't use the `GrimAC`. Do you have any solution apart from not using an anticheat like switching to a different anticheat or configuring `GrimAC` or any other anticheat to work right?

**Comment by Axionize** [comment]
The best I can tell you to do right now is to exempt your players from simulation with `grim.exempt.simulation` and any other movement check. 

We're working on it but we won't have a solution for a long time.

**Comment by Axionize** [comment]
@notstevy @TehNitro @Hwaanx 
I've pushed an attempt at fixing GrimAC incompatibility issues in my last few dev builds, test it out and tell me how it goes.


https://modrinth.com/plugin/knockbacksync

**Comment by Axionize** [comment]
Marking this as closed since I've yet to find a report of any AC issues on latest builds.
